--- Problem 2: Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
--- By considering the terms in the Fibonnaci sequence whose values do not exceed four million, find the sum of the even-valued terms.

--- Fibonacci sequence Defined
luc a b = a : luc b (a + b)
fibonnaciSeq n = take n (luc 0 1)

--- Solution
evenFib n = sum [x | x <- fibonnaciSeq n, even x] 
